name: "SMP"
version: "0.1"
main: "me.actuallysoheil.plugin.smp.SMPPlugin"
description: "A lightweight Minecraft PaperMC plugin designed for SMP servers."
author: "actuallySoheil"
website: "https://github.com/actuallySoheil/"
api-version: "26.1.2"