settings:
  database:
    # Format: mongodb://user:password@host:port/
    uri: "mongodb://admin:admin@localhost:27017/"
    name: "smp"

  team:
    # Allowed team id regex input for team creation. (Default: "^[a-zA-Z0-9_]+$")
    allowed-id-regex: "^[a-zA-Z0-9_]+$"
    # The max amount of characters for team id. (Default: 12)
    id-max-length: 12
    # The max amount of team size including team leader. (Default: 6)
    max-members: 6
    # The time (in seconds) player has to wait to create a team after disbanding one. (Default: 60)
    creation-cooldown-time-seconds: 60
    # The time (in seconds) player has to accept team invitations before they get expired. (Default: 60)
    invite-expiration-time-seconds: 60
    home:
      # The time (in seconds) player has to wait to teleport to team home again. (Default: 30)
      teleport-cooldown-time-seconds: 30
      # List of worlds team leader cannot set home inside.
      blacklisted-worlds:
        - "world_the_end"